a = "* 3 FETCH (UID 86 BODY[2] {14098006}/9j/4daNRXhpZgAASUkqAAgAAAANAAABBAABAAAAIBYAAAEBBAABAAAAmBAAAA8BAgAIAAAAqgAAABABAgAJAAAAsgAAABIBAwABAAAAAQAAABoBBQABAAAA3gAAABsBBQABAAAA5gAAACgBAwABAAAAAgAAADEBAgAOAAAAvAAAADIBAgAUAAAAygAAABMCAwABAAAAAQAAAGmHBAABAAAA7gAAACWIBAABAAAApgIAAAwDAABzYW1zdW5nAFNNLUE5MjBGAABBOTIwRlhYVTJCU0cxADIwMTk6MDg6MjIgMTY6MjY6NDgASAAAAAEAAABIAAAAAQAAABQAmoIFAAEAAABuAgAAnYIFAAEAAAB2AgAAIogDAAEAAAACAAAAJ4gDAAEAAABkAAAAAJAHAAQAAAAwMjIwA5ACABQAAABGAgAABJACABQAAABaAgAABZIFAAEAAAB+AgAA"
b = a.split("}")
c = b[0].split("{")
print(c[-1])
d = float(4096/int((c[-1])))
x = [1,2,3,4]
a = x
print(a)